#!/bin/bash

# This script assumes you use the autospeed.lua script.
# This was created because vdpau does not like when we switch monitors modes while mpv is running.

# Same as the autospeed.lua settings.
MIN=0.9
MAX=1.1

# Monitor connector name, find with xrandr --current
MONITOR="HDMI-0"

# Find modes with xrandr --verbose
# For example: "1920x1080 (0x281) 148.500MHz +HSync +VSync" for 60hz (2 lines under: clock  60.00Hz)
MODE24=""
MODE48=""
MODE50=""
MODE60="0x281"
MODE72="0x2d8"
MODE120=""

# Sets monitor refresh rate on exit. Set to "" to disable.
EXITMODE=$MODE60

# Seconds to sleep after setting the refresh rate.
# This is if you screen is slow to change modes, so you don't miss part of the video while the screen is blank.
SLEEP=4

checkMode () {
    if [[ "$1" == "" ]]; then return 0; fi
    if [[ "$3" -gt $(bc -l <<< "$2 * $MIN" | awk '{print int($1+0.5)}') ]] && [[ "$3" -lt $(bc -l <<< "$2 * $MAX" | awk '{print int($1+0.5)}') ]]; then
        MODE=$1
        return 1
    fi
    return 0
} 

MODE=0
for arg in "$@"; do
    if [[ -f "$arg" ]]; then
        fr=$(ffprobe -v quiet -select_streams v -show_entries stream=r_frame_rate "$(realpath "$arg")" | grep -Po "\d+/\d+")
        if [[ "$fr" == "" ]]; then break; fi

        fr=$(bc -l <<< "$(echo $fr | cut -f 1 -d/) / $(echo $fr | cut -f 2 -d/)" | awk '{print int($1+0.5)}')
        if [[ "$fr" =~ "^[0-9.]+$" ]]; then break; fi

        checkMode $MODE24 24 $fr
        if [[ "$?" == 1 ]]; then break; fi
        checkMode $MODE48 24 $fr
        if [[ "$?" == 1 ]]; then break; fi
        checkMode $MODE48 48 $fr
        if [[ "$?" == 1 ]]; then break; fi
        checkMode $MODE50 25 $fr
        if [[ "$?" == 1 ]]; then break; fi
        checkMode $MODE50 50 $fr
        if [[ "$?" == 1 ]]; then break; fi
        checkMode $MODE60 30 $fr
        if [[ "$?" == 1 ]]; then break; fi
        checkMode $MODE60 60 $fr
        if [[ "$?" == 1 ]]; then break; fi
        checkMode $MODE72 24 $fr
        if [[ "$?" == 1 ]]; then break; fi
        checkMode $MODE120 120 $fr
        if [[ "$?" == 1 ]]; then break; fi

        break
    fi
done

if [[ "$MODE" > 0 ]]; then
    xrandr --output $MONITOR --mode $MODE
    if [[ "$SLEEP" > 0 ]]; then
        sleep $SLEEP
    fi
fi

mpv "$@"

if [[ "$MODE" > 0 ]] && [[ "$EXITMODE" != "" ]]; then
    xrandr --output $MONITOR --mode $EXITMODE
fi
